version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.19.8
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './persistent'
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      OPENAI_APIKEY: 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
      CLUSTER_HOSTNAME: 'node1'